### ISSUE TITLE
Cannot find module 'financial' or its corresponding type declarations.

### ISSUE THREAD

**Issue by andylacko** [lmammino/financial#21]
<img width="789" alt="image" src="https://github.com/lmammino/financial/assets/7139923/f6469fb7-0856-40ad-b9b1-0b39275f0244">

### Issue
when updated to 0.2.1, I can not longer import ppmt from module, actually, the module can not be found

### env
pnpm
node v21.6.2

**Comment by lmammino** [comment]
Hey @andylacko , thanks a million for reporting this. I had significantly updated the publishing pipeline and somehow I accidentally removed the build step from it 😓 

It should be fixed now in `0.2.2`. Please let me know if you encounter other issues!

Thanks once more

**Comment by andylacko** [comment]
Yes, works like charm. Thank you for instant response and fix 💪
